### ISSUE TITLE
Event flexibility

### ISSUE THREAD

**Issue by amiller47** [Hazmit/fcc_register_bugs#25]
We need to have more flexibility for events to register an individual or team and collect additional information   

Army - AF for example.  The old site was easy to add additional fields to collect information.  In this case Army or AF team?  Do you need to attend the learn to curl? ….and more.

**Comment by Hazmit** [comment]
So you are saying you need to be able to create a custom questionnaire that is unique per event?

**Comment by Hazmit** [comment]
Resolving this item as it has been addressed with questions feature that is live.
