### ISSUE TITLE
Looking for Group - Contact

### ISSUE THREAD

**Issue by fcc-drawmaster** [Hazmit/fcc_register_bugs#34]
Recommend adding a primary contact for this feature instead of the generic "Drawmaster".

**Comment by Hazmit** [comment]
Is there a place you are seeing the drawmaster e-mail?
I'm looking through the interface and it looks like we haven't put one anywhere.

**Comment by fcc-drawmaster** [comment]
I believe it was on the contact page.

**Comment by fcc-drawmaster** [comment]
If Larry is doing the find people a team job then we should just point
towards him. He seems fine with his contact info on the bottom of the live
website.

**Comment by Hazmit** [comment]
I'm not sure what you mean. The form takes in information. Larry can see
that information in the admin side of the site, Larry will reach out and
work with people to put them on teams. What is pointing people to you?

**Comment by fcc-drawmaster** [comment]
On the form page “Drawmasters will do their best to find other curlers
looking for a team to pair you up with”

Unless Larry is now a drawmaster

**Comment by Hazmit** [comment]
Larry is now a draw master.

**Comment by Hazmit** [comment]
Resolving this item nothing to fix.
