### ISSUE TITLE
Account Profile

### ISSUE THREAD

**Issue by fcc-drawmaster** [Hazmit/fcc_register_bugs#40]
When registering for leagues there is a My Teams area in your profile to see which you have signed up for. Is there intent to have something similar for events?
The registration process creates an account, but doesn't give you any information if you only signed up for events and not leagues.

**Comment by Hazmit** [comment]
Actually yes!
I need to add a side bar link for events and it will list your "teams" for events and then your individual events such as learn to curls. I should probably rename the my teams to my leagues once I do that.

good find.

**Comment by Hazmit** [comment]
This has been added to the side bar for people who are logged in.
