### ISSUE TITLE
Leagues > Teams not showing seperate team list

### ISSUE THREAD

**Issue by kjspaleta** [Hazmit/fcc_register_bugs#56]
when multiple teams have signed up for a night on the leagues >teams they're all smooshed together. Need a carriage return or something.
![image](https://github.com/Hazmit/fcc_register_bugs/assets/116228958/20187508-99c1-491d-a260-44686fa80626)

**Comment by Hazmit** [comment]
I'll fix this right now!
Need to be in a separate <div>

**Comment by Hazmit** [comment]
It's funny it always looked right on my screen because I happened to have
the window large enough to float four people.

[image: image.png]

**Comment by Hazmit** [comment]
This has been resolved and is live.
