### ISSUE TITLE
view/register event page while is spewing code

### ISSUE THREAD

**Issue by kjspaleta** [Hazmit/fcc_register_bugs#57]
![image](https://github.com/Hazmit/fcc_register_bugs/assets/116228958/d769b55c-9a72-47d7-8193-570c19491f1b)

firefox on windows 10

any event that has nonzero participants signed up looks similar.  Zero participant events look okay.

Looks the same independent of being logged in.

**Comment by kjspaleta** [comment]
Also I'm not sure if people who are signing their names up for  LTC will want their names shown publicly. I'm not sure I'd be okay with that.

**Comment by Hazmit** [comment]
This has been resolved. To fix both issues I removed the team listing from the page and it only shows for admins. I pushed this to the live site. Also resolves the problem with showing registered users to public. So public can no longer see.
