### ISSUE TITLE
5 & Under Event Page

### ISSUE THREAD

**Issue by dhejna** [Hazmit/fcc_register_bugs#60]
1) Can we make the teams' home club be visible on the site?
2) Can the format be changed so that the list of teams can be listed similar to how they are on our league pages? (Team name, Home club : Player 1, player 2, etc.......)
3) I think as of Oct 1, the Mass team (Nathan Woolsey) is not transferred over from the old site.
4) Site says 12/24 slots taken. Obviously this is reflecting 12 players signed up. Can we switch to #teams/24 teams?

Will send a new flyer once I make one and we can replace the one we have. I might just redo the whole thing.... I know I need to fix the typo I made - (Nationals is in April - not May.)

![woolsey](https://github.com/Hazmit/fcc_register_bugs/assets/146140039/db6dbdf6-4f82-4a0c-8c62-e9ad7827da0a)

**Comment by dhejna** [comment]
Do other admins have the capability of adding hero images? I didn't see an upload button to add the new flyer.

**Comment by dhejna** [comment]
When I go in to edit the 5U info blurb and add a space between each line it doesn't carry over when I view it later.
Might look nicer if it wasn't one big paragraph.

**Comment by Hazmit** [comment]
This one is actually a bit more difficult than it seems. Right now the form
captures text and saves it in the database with limited ability to define
formatting. To make this more flexible we need to implement a WYSYWIG (What
you see is what you get) editor interface in the application. We would need
to use a product like "tiny mce" which provides an interface for text input
that would allow formatting to be captured in the saved text.

**Comment by dhejna** [comment]
@Hazmit 
Minor typo: Maggie Woolsey should be Nathan Woolsey

**Comment by dhejna** [comment]
![Fairbanks5U2024](https://github.com/Hazmit/fcc_register_bugs/assets/146140039/17d38e5d-afbe-410e-bb37-700a09bfaf0b)
Also, this is the new-er flyer

**Comment by Hazmit** [comment]
Closing this one out as we have added wysiwig editing and also the new flyer is up!
