### ISSUE TITLE
Spring Sunday doubles league description error

### ISSUE THREAD

**Issue by kjspaleta** [Hazmit/fcc_register_bugs#62]
Sunday doubles league is listed as happening on Friday at 6 PM. I believe you mean Sunday at 6 PM https://curlfairbanks.org/leagues
![image](https://github.com/Hazmit/fcc_register_bugs/assets/116228958/5269b18b-ae07-42f2-a8a3-ca4072c47957)

**Comment by Hazmit** [comment]
Fixed!
