### ISSUE TITLE
League cards proportions are whacked on register>league start page

### ISSUE THREAD

**Issue by kjspaleta** [Hazmit/fcc_register_bugs#63]
https://curlfairbanks.org/register/league-start

I think the boxes need to be longer to accommodate the extra verbiage.

![image](https://github.com/Hazmit/fcc_register_bugs/assets/116228958/0ef1a578-a312-4299-9a80-1ca620ab0407)

**Comment by Hazmit** [comment]
This has been resolved with updates made last night. All cards for league selection are 100% width now.
